modify thanks to, files README.md & docs/index.md
unbalancedparentheses/data_science_in_julia_for_hackers pull request #37
Opened 2021-02-19 20:32 UTC by pefontana

2021-02-19 20:37 UTC, marianLambda approved these changes

2021-02-19 20:53 UTC, martinacantaro requested changes

2021-02-19 20:53 UTC, martinacantaro commented on README.md
> +Thanks to Martina Cantaro, Camilo Plata, Manuel Puebla, Lucas Raul Fernandez Piana, Osvaldo Martin, Iñaki Garay and Mariana Vinyolas.
don't forget the tilde in Raúl

2021-02-19 21:12 UTC, pefontana commented on README.md
> +Thanks to Martina Cantaro, Camilo Plata, Manuel Puebla, Lucas Raul Fernandez Piana, Osvaldo Martin, Iñaki Garay and Mariana Vinyolas.
Done it!

2021-02-22 15:32 UTC, marianLambda approved these changes

2021-02-23 13:53 UTC, martinacantaro approved these changes

2021-02-23 13:53 UTC, merged