delete okeys
unbalancedparentheses/data_science_in_julia_for_hackers pull request #38
Opened 2021-02-22 18:46 UTC by pefontana

I delete the "okeys" and variants from the book, except for chapter one because Herman is working on it

2021-02-22 19:15 UTC, marianLambda commented
a suggestion for commiting: it is good to commit often. As an example, you may want to make a commit each time you finish deleting "okeys" in a chapter and then go to the next one.
Try making a commit every time you finish a "unit" of your work.

2021-02-23 14:56 UTC, martinacantaro requested changes
The HTML files contain errors, please generate them again

2021-02-23 14:56 UTC, martinacantaro commented on 12_ultima_continued/12_ultima_continued.jl
> +After the champagne, hugs and a little celebration Garriot return to the work and start to analize the metrics to see if everything is good, and it does. He relax a little bit until something calls h
change "good" for "alright"

2021-02-24 14:58 UTC, pefontana commented
HTML files are corrected and I made the change grammar changes you suggested


Can someone review them?

2021-02-24 18:26 UTC, marianLambda approved these changes

2021-02-24 21:04 UTC, martinacantaro approved these changes

2021-02-24 21:04 UTC, merged