Chapter 3: Summary added
unbalancedparentheses/data_science_in_julia_for_hackers pull request #49
Opened 2021-03-03 15:34 UTC by pefontana

2021-03-03 20:58 UTC, marianLambda requested changes

2021-03-03 20:58 UTC, marianLambda commented on 03_probability_intro/03_probability_intro.jl
> +In this chapter we start showing the basics concepts of statistics.
more details about the concepts of probability that were discussed would be nice. For example:
> ...we have talked about probability of independent events and also conditional probability...

2021-03-03 20:58 UTC, marianLambda commented on 03_probability_intro/03_probability_intro.jl
> +In this chapter we start showing the basics concepts of statistics.
remember to write in past or present perfect tense, since we are talking about what we have already discussed in the chapter.

2021-03-03 20:58 UTC, marianLambda commented on 03_probability_intro/03_probability_intro.jl
> +Then we see how we can approach problems in a Bayesian way. How our first beliefs on a hypothesis can be updated with the income of new data and the most common probability distribution plots, that i
check tense

2021-03-03 20:58 UTC, marianLambda commented on 03_probability_intro/03_probability_intro.jl
> +Then we see how we can approach problems in a Bayesian way. How our first beliefs on a hypothesis can be updated with the income of new data and the most common probability distribution plots, that i
change:
> Then we see how we can approach problems in a Bayesian way. How our first beliefs on a hypothesis can be updated with the income of new data

to something like:
> Then we addressed the different approaches on probability, in particular the Bayesian approach and how our initial beliefs can be updated with the income of new data. Some common probability distribution functions are presented too.

2021-03-03 20:58 UTC, marianLambda commented on 03_probability_intro/03_probability_intro.jl
> +At last, we solve the multi-armed bandit problem thinking in a Bayesian way.
I think it will be better to change 
> At last,

to
> Finally

or something similar.

2021-03-03 20:58 UTC, marianLambda commented on 03_probability_intro/03_probability_intro.jl
> +At last, we solve the multi-armed bandit problem thinking in a Bayesian way.
check tense

2021-03-03 20:58 UTC, marianLambda commented on 03_probability_intro/03_probability_intro.jl
> +At last, we solve the multi-armed bandit problem thinking in a Bayesian way.
try giving some little more detail about the problem context and solution in a very high-level.

2021-03-11 18:36 UTC, martinacantaro requested changes

2021-03-11 18:36 UTC, martinacantaro commented on 03_probability_intro/03_probability_intro.jl
> +We talked about probability of independent events and also conditional probability to arrive at the Bayes' theorem.
> We talked about the probability of independent events and about conditional probability, which led us to Bayes' theorem.

2021-03-11 18:36 UTC, martinacantaro commented on 03_probability_intro/03_probability_intro.jl
> +We also learned what is a probability distribution giving some examples and why Bayesians use them to represent probability.
> We also learned what a probability distribution is, we went over a few examples and saw why Bayesians use them to represent probability.

2021-03-11 18:36 UTC, martinacantaro commented on 03_probability_intro/03_probability_intro.jl
> +Finally, we saw the multi-armed bandit problem where with a limited amount of casino chips we want to estimate the best win probability of 3 slot machines.
Instead of describing the casino example, remind the reader what a multi-armed bandit problem is

2021-03-11 18:36 UTC, martinacantaro commented on 03_probability_intro/03_probability_intro.jl
> +Then we addressed the two main approaches to probability, the frequentist approach and in particular the Bayesian one where our initial beliefs can be updated with the income of new data.
>  Then, we addressed the two main approaches to probability: the frequentist approach and the Bayesian one, where our initial beliefs can be updated with the addition of new data.

2021-03-11 18:36 UTC, martinacantaro commented on 03_probability_intro/03_probability_intro.jl
> +To solved it we constructed a Bayesian model using the Thompson sampling algorithm.
Attention to detail: "To solve", not "to solved"

2021-03-12 17:01 UTC, martinacantaro requested changes

2021-03-12 17:01 UTC, martinacantaro commented on 03_probability_intro/03_probability_intro.jl
> +To solve it we constructed a Bayesian model using the Thompson sampling algorithm.
To solve it,

(add comma)

2021-03-12 17:01 UTC, martinacantaro commented on 03_probability_intro/03_probability_intro.jl
> +Finally, we saw the multi-armed bandit problem in which we have a limited amount of resources and must allocate them between competing alternatives to infer the one with the highest success probabili
must allocate them among competing alternatives

2021-03-31 18:04 UTC, merged